version: '2'
services:
  db:
    build:
      context: ./
      dockerfile: mysql.docker
    volumes:
      - "./data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    image: wordpress:latest
    restart: always
    links:
      - db
    environment:
      - VIRTUAL_HOST=wordpress
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_PASSWORD=wordpress

networks:
  default:
    external:
      name: services_link
